#############################################################################
# Makefile for building: sqlitebrowser
# Generated by qmake (2.01a) (Qt 4.8.7) on: Mon Apr 25 17:09:44 2016
# Project:  sqlitebrowser.pro
# Template: subdirs
# Command: /usr/local/bin/qmake -o Makefile sqlitebrowser.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-libs-antlr-2-7-7-antlr-pro \
		sub-libs-qhexedit-qhexedit-pro \
		sub-libs-qcustomplot-source-qcustomplot-pro \
		sub-libs-qscintilla-Qt4Qt5-qscintilla-pro \
		sub-src

libs/antlr-2.7.7/$(MAKEFILE).antlr: 
	@$(CHK_DIR_EXISTS) libs/antlr-2.7.7/ || $(MKDIR) libs/antlr-2.7.7/ 
	cd libs/antlr-2.7.7/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/libs/antlr-2.7.7/antlr.pro -o $(MAKEFILE).antlr
sub-libs-antlr-2-7-7-antlr-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs/antlr-2.7.7/ || $(MKDIR) libs/antlr-2.7.7/ 
	cd libs/antlr-2.7.7/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/libs/antlr-2.7.7/antlr.pro -o $(MAKEFILE).antlr
sub-libs-antlr-2-7-7-antlr-pro: libs/antlr-2.7.7/$(MAKEFILE).antlr FORCE
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr
sub-libs-antlr-2-7-7-antlr-pro-make_default: libs/antlr-2.7.7/$(MAKEFILE).antlr FORCE
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr 
sub-libs-antlr-2-7-7-antlr-pro-make_first: libs/antlr-2.7.7/$(MAKEFILE).antlr FORCE
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr first
sub-libs-antlr-2-7-7-antlr-pro-all: libs/antlr-2.7.7/$(MAKEFILE).antlr FORCE
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr all
sub-libs-antlr-2-7-7-antlr-pro-clean: libs/antlr-2.7.7/$(MAKEFILE).antlr FORCE
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr clean
sub-libs-antlr-2-7-7-antlr-pro-distclean: libs/antlr-2.7.7/$(MAKEFILE).antlr FORCE
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr distclean
sub-libs-antlr-2-7-7-antlr-pro-install_subtargets: libs/antlr-2.7.7/$(MAKEFILE).antlr FORCE
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr install
sub-libs-antlr-2-7-7-antlr-pro-uninstall_subtargets: libs/antlr-2.7.7/$(MAKEFILE).antlr FORCE
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr uninstall
libs/qhexedit/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libs/qhexedit/ || $(MKDIR) libs/qhexedit/ 
	cd libs/qhexedit/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/libs/qhexedit/qhexedit.pro -o $(MAKEFILE)
sub-libs-qhexedit-qhexedit-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs/qhexedit/ || $(MKDIR) libs/qhexedit/ 
	cd libs/qhexedit/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/libs/qhexedit/qhexedit.pro -o $(MAKEFILE)
sub-libs-qhexedit-qhexedit-pro: libs/qhexedit/$(MAKEFILE) FORCE
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE)
sub-libs-qhexedit-qhexedit-pro-make_default: libs/qhexedit/$(MAKEFILE) FORCE
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) 
sub-libs-qhexedit-qhexedit-pro-make_first: libs/qhexedit/$(MAKEFILE) FORCE
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) first
sub-libs-qhexedit-qhexedit-pro-all: libs/qhexedit/$(MAKEFILE) FORCE
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) all
sub-libs-qhexedit-qhexedit-pro-clean: libs/qhexedit/$(MAKEFILE) FORCE
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-qhexedit-qhexedit-pro-distclean: libs/qhexedit/$(MAKEFILE) FORCE
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-qhexedit-qhexedit-pro-install_subtargets: libs/qhexedit/$(MAKEFILE) FORCE
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) install
sub-libs-qhexedit-qhexedit-pro-uninstall_subtargets: libs/qhexedit/$(MAKEFILE) FORCE
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) uninstall
libs/qcustomplot-source/$(MAKEFILE).qcustomplot: 
	@$(CHK_DIR_EXISTS) libs/qcustomplot-source/ || $(MKDIR) libs/qcustomplot-source/ 
	cd libs/qcustomplot-source/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/libs/qcustomplot-source/qcustomplot.pro -o $(MAKEFILE).qcustomplot
sub-libs-qcustomplot-source-qcustomplot-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs/qcustomplot-source/ || $(MKDIR) libs/qcustomplot-source/ 
	cd libs/qcustomplot-source/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/libs/qcustomplot-source/qcustomplot.pro -o $(MAKEFILE).qcustomplot
sub-libs-qcustomplot-source-qcustomplot-pro: libs/qcustomplot-source/$(MAKEFILE).qcustomplot FORCE
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot
sub-libs-qcustomplot-source-qcustomplot-pro-make_default: libs/qcustomplot-source/$(MAKEFILE).qcustomplot FORCE
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot 
sub-libs-qcustomplot-source-qcustomplot-pro-make_first: libs/qcustomplot-source/$(MAKEFILE).qcustomplot FORCE
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot first
sub-libs-qcustomplot-source-qcustomplot-pro-all: libs/qcustomplot-source/$(MAKEFILE).qcustomplot FORCE
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot all
sub-libs-qcustomplot-source-qcustomplot-pro-clean: libs/qcustomplot-source/$(MAKEFILE).qcustomplot FORCE
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot clean
sub-libs-qcustomplot-source-qcustomplot-pro-distclean: libs/qcustomplot-source/$(MAKEFILE).qcustomplot FORCE
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot distclean
sub-libs-qcustomplot-source-qcustomplot-pro-install_subtargets: libs/qcustomplot-source/$(MAKEFILE).qcustomplot FORCE
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot install
sub-libs-qcustomplot-source-qcustomplot-pro-uninstall_subtargets: libs/qcustomplot-source/$(MAKEFILE).qcustomplot FORCE
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot uninstall
libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla: 
	@$(CHK_DIR_EXISTS) libs/qscintilla/Qt4Qt5/ || $(MKDIR) libs/qscintilla/Qt4Qt5/ 
	cd libs/qscintilla/Qt4Qt5/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/libs/qscintilla/Qt4Qt5/qscintilla.pro -o $(MAKEFILE).qscintilla
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs/qscintilla/Qt4Qt5/ || $(MKDIR) libs/qscintilla/Qt4Qt5/ 
	cd libs/qscintilla/Qt4Qt5/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/libs/qscintilla/Qt4Qt5/qscintilla.pro -o $(MAKEFILE).qscintilla
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla FORCE
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-make_default: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla FORCE
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla 
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-make_first: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla FORCE
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla first
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-all: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla FORCE
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla all
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-clean: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla FORCE
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla clean
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-distclean: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla FORCE
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla distclean
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-install_subtargets: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla FORCE
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla install
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-uninstall_subtargets: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla FORCE
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla uninstall
src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /Users/nick/Desktop/sqlitebrowse/sqlitebrowser-retina-support/src/src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: sqlitebrowser.pro  /usr/local/Cellar/qt/4.8.7_2/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.7_2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/debug_and_release.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile sqlitebrowser.pro
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/debug_and_release.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.7_2/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile sqlitebrowser.pro

qmake_all: sub-libs-antlr-2-7-7-antlr-pro-qmake_all sub-libs-qhexedit-qhexedit-pro-qmake_all sub-libs-qcustomplot-source-qcustomplot-pro-qmake_all sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-qmake_all sub-src-qmake_all FORCE

make_default: sub-libs-antlr-2-7-7-antlr-pro-make_default sub-libs-qhexedit-qhexedit-pro-make_default sub-libs-qcustomplot-source-qcustomplot-pro-make_default sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-make_default sub-src-make_default FORCE
make_first: sub-libs-antlr-2-7-7-antlr-pro-make_first sub-libs-qhexedit-qhexedit-pro-make_first sub-libs-qcustomplot-source-qcustomplot-pro-make_first sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-make_first sub-src-make_first FORCE
all: sub-libs-antlr-2-7-7-antlr-pro-all sub-libs-qhexedit-qhexedit-pro-all sub-libs-qcustomplot-source-qcustomplot-pro-all sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-all sub-src-all FORCE
clean: sub-libs-antlr-2-7-7-antlr-pro-clean sub-libs-qhexedit-qhexedit-pro-clean sub-libs-qcustomplot-source-qcustomplot-pro-clean sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-clean sub-src-clean FORCE
distclean: sub-libs-antlr-2-7-7-antlr-pro-distclean sub-libs-qhexedit-qhexedit-pro-distclean sub-libs-qcustomplot-source-qcustomplot-pro-distclean sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-distclean sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libs-antlr-2-7-7-antlr-pro-install_subtargets sub-libs-qhexedit-qhexedit-pro-install_subtargets sub-libs-qcustomplot-source-qcustomplot-pro-install_subtargets sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-install_subtargets sub-src-install_subtargets FORCE
uninstall_subtargets: sub-libs-antlr-2-7-7-antlr-pro-uninstall_subtargets sub-libs-qhexedit-qhexedit-pro-uninstall_subtargets sub-libs-qcustomplot-source-qcustomplot-pro-uninstall_subtargets sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-uninstall_subtargets sub-src-uninstall_subtargets FORCE

sub-libs-antlr-2-7-7-antlr-pro-sub_Debug: libs/antlr-2.7.7/$(MAKEFILE).antlr
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr debug
sub-libs-qhexedit-qhexedit-pro-sub_Debug: libs/qhexedit/$(MAKEFILE)
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) debug
sub-libs-qcustomplot-source-qcustomplot-pro-sub_Debug: libs/qcustomplot-source/$(MAKEFILE).qcustomplot
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot debug
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-sub_Debug: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla debug
sub-src-sub_Debug: src/$(MAKEFILE)
	cd src/ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-libs-antlr-2-7-7-antlr-pro-sub_Debug sub-libs-qhexedit-qhexedit-pro-sub_Debug sub-libs-qcustomplot-source-qcustomplot-pro-sub_Debug sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-sub_Debug sub-src-sub_Debug

sub-libs-antlr-2-7-7-antlr-pro-sub_Release: libs/antlr-2.7.7/$(MAKEFILE).antlr
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr release
sub-libs-qhexedit-qhexedit-pro-sub_Release: libs/qhexedit/$(MAKEFILE)
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) release
sub-libs-qcustomplot-source-qcustomplot-pro-sub_Release: libs/qcustomplot-source/$(MAKEFILE).qcustomplot
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot release
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-sub_Release: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla release
sub-src-sub_Release: src/$(MAKEFILE)
	cd src/ && $(MAKE) -f $(MAKEFILE) release
release: sub-libs-antlr-2-7-7-antlr-pro-sub_Release sub-libs-qhexedit-qhexedit-pro-sub_Release sub-libs-qcustomplot-source-qcustomplot-pro-sub_Release sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-sub_Release sub-src-sub_Release

sub-libs-antlr-2-7-7-antlr-pro-check: libs/antlr-2.7.7/$(MAKEFILE).antlr
	cd libs/antlr-2.7.7/ && $(MAKE) -f $(MAKEFILE).antlr check
sub-libs-qhexedit-qhexedit-pro-check: libs/qhexedit/$(MAKEFILE)
	cd libs/qhexedit/ && $(MAKE) -f $(MAKEFILE) check
sub-libs-qcustomplot-source-qcustomplot-pro-check: libs/qcustomplot-source/$(MAKEFILE).qcustomplot
	cd libs/qcustomplot-source/ && $(MAKE) -f $(MAKEFILE).qcustomplot check
sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-check: libs/qscintilla/Qt4Qt5/$(MAKEFILE).qscintilla
	cd libs/qscintilla/Qt4Qt5/ && $(MAKE) -f $(MAKEFILE).qscintilla check
sub-src-check: src/$(MAKEFILE)
	cd src/ && $(MAKE) -f $(MAKEFILE) check
check: sub-libs-antlr-2-7-7-antlr-pro-check sub-libs-qhexedit-qhexedit-pro-check sub-libs-qcustomplot-source-qcustomplot-pro-check sub-libs-qscintilla-Qt4Qt5-qscintilla-pro-check sub-src-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

